### ISSUE TITLE
Русская версия выглядит как исходник в MD

### ISSUE THREAD

**Issue by petRUShka** [arbox/ruby-style-guide#37]
Когда я нажимаю на ссылку "русский (данный документ)" я, вместо ожидаемого скомпилированного и красивого руководства, попадаю на исходник.

![2017-03-21-221221_1017x443_scrot](https://cloud.githubusercontent.com/assets/146893/24166164/dab71ca6-0e8b-11e7-934a-f82cd4751ea9.png)

В то время, как в версиях на других языках, всё ок:

![2017-03-21-221336_1056x574_scrot](https://cloud.githubusercontent.com/assets/146893/24166225/06b41106-0e8c-11e7-883c-632a83f02efb.png)

**Comment by petRUShka** [comment]
P.S. проблема не только у меня.

**Comment by arbox** [comment]
@petRUShka, спасибо за сообщение об ошибке. Проблема на стороне ГитХаба, написал им в техподдержку, будем с ними общаться.

**Comment by arbox** [comment]
ГитХаб не хочет правильно отображать большие файлы. Общаемся по поводу исключений для данного проекта.

**Comment by petRUShka** [comment]
Отлично!

А развые ваш проект больше оригинального на английском?

**Comment by installero** [comment]
Друзья, я считаю, что дело не в длине файла. На 472-й строке был какой-то странный символ, если его убрать, файл [отображается](https://github.com/installero/ruby-style-guide/blob/63eb0c863937b5aa9a7285900db7fa30327858ce/README-ruRU.md) как надо.

**Comment by arbox** [comment]
Solved! Thank you all for the participation! :)
