### ISSUE TITLE
Скобки вокруг аргументов в примерах

### ISSUE THREAD

**Issue by izeal** [arbox/ruby-style-guide#40]
В главе Синтаксис у метода `is_a?` в одном случае у аргумента стоят скобки, в другом нет - поправьте

Также в главе Числа не стоят скобки у аргумента

**Comment by arbox** [comment]
Большое спасибо за вашу внимательность!

Подобные нарушения единообразия не являются признаками хорошего стиля. Однако мы придерживаемся при переводе той формы, которая стоит в оригинале руководства. Когда это будет изменено в английской версии, мы исправим примеры и в переводе.

Если у вас будет время, попробуйте внести правки в оригинал. Раз в неделю в пятницу все изменения из оригинала переходят и в перевод.

**Comment by izeal** [comment]
туда тоже написал, но там пока не ответили
